- includes/Blocks/CoreCode.php
- includes/Blocks/CoreColumn.php
- includes/Blocks/CoreImage.php
This PR removed the erroneous `style` fields added on some blocks as they create issues with WPGraphQL type checking.
> Chore: Remove Extra Block `style` fields

- includes/Data/ContentBlocksResolver.php
This PR adds the `wpgraphql_content_blocks_resolver_content` filter to allow users to set the `$content` passed to `parse_blocks()` in `ContentBlocksResolver::resolve_content_blocks()`.
This filter is useful for adding block support via `NodeWithContentBlocks` on objects that dont use the built-in `Post` model.
```php
/**
* Gets the content from the model for parsing by WPGraphQL ContentBlocks.
*
* @param string $content The content to parse.
* @param \WPGraphQL\Model\Model $model The model to get content from.
*/
public static function get_content_from_model( $content, $model ) {
if ( $model instanceof TemplatePart ) {
$content = $model->content ?: '';
}
return $content;
}
```
> dev: filter content before parse_blocks()

- composer.json
This PR sets the Composer package type to "wordpress-plugin", so dependents can autoinstall the plugin in `wp-content/plugins` directory using the `extra.installer-paths` property.
> dev: add package type to composer.json

- README.md
- includes/Blocks/Block.php
- includes/Registry/Registry.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- tests/unit/BlockAttributesObjectTest.php
- tests/unit/BlockQueriesTest.php
- tests/unit/ContentBlockInterfaceTest.php
- tests/unit/RegistryTestCase.php
- tests/unit/UnknownBlockTest.php
This PR changes `contentBlocks` field to `editorBlocks` in all places including the documentation
[MERL-727](https://wpengine.atlassian.net/browse/MERL-727)
* Load GraphQLi
* Check that the old field is not available
* Check that the new field is available.
[MERL-727]: https://wpengine.atlassian.net/browse/MERL-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BREAKING! Refactor: Change contentBlocks -> editorBlocks

- README.md
- includes/Data/ContentBlocksResolver.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- tests/unit/BlockQueriesTest.php
- tests/unit/ContentBlockInterfaceTest.php
- tests/unit/UnknownBlockTest.php
This PR causes a BREAKING change:
It changes `nodeId` -> `clientId` and `parentId` -> `parentClientId` as per recommendation 
https://github.com/wpengine/wp-graphql-content-blocks/issues/15
Make sure you check that the new fields are `clientId` and `parentClientId` on the `contentBlocks`
> [Merl 726] - BREAKING! Change `nodeId` -> `clientId` and `parentId` -> `parentClientId`

- composer.json
- composer.lock
Made `imangazaliev/didom` a dependency instead of a `devDependencies`. This make it so `composer install --no-dev` can be used, leaving linting and testing package uninstalled. Currently if I run `composer install --no-dev` any queries include `attributes` fails over the missing `imangazaliev/didom` package.
> `composer install --no-dev` fix

- includes/Blocks/Block.php
I noticed this error in my Docker console as I would run queries with `editorBlocks` in them, so I just moved the assignment of `$default` above the `if` statement in the `Block::resolve_block_attributes()` function, replaced the following usages of `$attribute_config['default']` with `$default`.
> fix: illegal index error fixed in Block.php

- .changeset/flat-drinks-unite.md
- .github/workflows/release.yml
- .gitignore
- README.md
- package-lock.json
- package.json
This PR removes the `composer install` step by zipping the final plugin dist and uploading it to the GitHub release upon a successful Changesets release.
Users will be able to visit the [releases](https://github.com/wpengine/wp-graphql-content-blocks/releases) tab and get the source code as they could before, which is an exact representation of the GitHub repo, as well as download the `wp-graphql-content-blocks.zip` plugin file, which includes the prod `vendor` directory, and all other [required dist files as specified in the package.json.](https://github.com/wpengine/wp-graphql-content-blocks/blob/remove-compser-step/package.json#L22-L29)
> Bundle `vendor` in the final plugin .zip (Remove Composer step)

- .changeset/smooth-deers-admire.md
- includes/Data/ContentBlocksResolver.php
- tests/unit/BlockQueriesTest.php
This PR is for one of two to fulfill [MERL-759](https://wpengine.atlassian.net/jira/software/c/projects/MERL/boards/1007?modal=detail&selectedIssue=MERL-759). It sets editorBlocks to use ( flat: true ) by default. The test case for a non-flattened  editor block was also updated to have the `flat` arg set to explicitly false.
[MERL-759]: https://wpengine.atlassian.net/browse/MERL-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
To test: 
Spin up a site in Local and add the most recent `wp-graphql-content-blocks` plugin to the plugin folder.
After installing Faust and WPGraphQL, head to posts and create a gallery of photos.
Check `editorBlocks` in the GraphiQL IDE returns a flat list of blocks:
> Changed flatlist to true by default

- .github/workflows/release.yml
- README.md
As @TeresaGobble begins working on a way to get automatic updates from GitHub, we need a consistency named .zip file for the updater to grab. Changing the artifact name to `wp-graphql-content-blocks.zip`.
> Change artifact name and readme links

- .changeset/lovely-doors-hammer.md
- includes/WPGraphQLContentBlocks.php
It's sometimes habit to download the `main` .zip from GitHub without actually downloading the production version from the "releases" tab. This PR adds a warning if the prod `vendor` directory isn't found and instructs the user to either run `composer install` if they meant to download the source code or download the production ready version from the releases tab.
> Warn the user if they downloaded the source code .zip

- includes/Blocks/Block.php
- includes/Data/ContentBlocksResolver.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- includes/Type/InterfaceType/PostTypeBlockInterface.php
- tests/unit/BlockSupportsAnchorTest.php
- tests/unit/ContentBlocksResolverTest.php
This PR adds support for querying Classic Blocks. Since those blocks are not stored in the database with a proper name we assign them a name now and resolve them as `CoreFreeForm` returning the contents of the innerHTML as long as the contents are not empty.
1. Create a Classic block in a post
2. Query for the `content` attribute in editor blocks.
4. Block should resolve as `CoreFreeForm` as plain HTML.
> [Merl-862] Add support for Classic Blocks

- .changeset/quiet-insects-mate.md
- includes/Field/BlockSupports/Anchor.php
- includes/utilities/DomHelpers.php
- tests/unit/BlockSupportsAnchorTest.php
Bug fix for https://github.com/wpengine/wp-graphql-content-blocks/issues/62
Uses a special case for parsing `Anchor` fields. Instead of searching the whole block HTML we search for the first node id attribute.
> Bug: inner blocks "anchor" field being applied to parent block resulting in duplicates

- .changeset/flat-buttons-shake.md
- tests/unit/DOMHelpersTest.php
- tests/unit/RegistryTestCase.php
This PR
1. Renames `WPGraphQL\ContentBlocks\Unit\RegistryTest` to `RegistryTestCase` to comply with PSR-4 autoloading.
2. Lints `DOMHelperTest` _using PHPCBF only_.
**Note:** The `composer.lock` file was _not_ regenerated, since I don't know what version of PHP ya'll are using to compile (to be addressed in a separate PR).
IDK what happened to the PR template, but
> tests: fix Unit test autoloading and lint

- .changeset/two-numbers-end.md
- composer.json
- composer.lock
This PR sets the minimum PHP version in `composer.json`, to ensure that all local dependency builds are using the same version instead of the user's current PHP version.
This should help prevent PHP incompatibilities / breaking changes from going under the radar (e.g. #68), as well as ensure that any commits to `composer.lock` are valid regardless of the user's local env (e.g. #69 ).
*Note*:
- Currently the minimum PHP requirement (`require->php` is set to 7.2 (per the readme.txt), despite the fact that the current codebase (per phpcs) is only compatible with PHP 7.4.
- The platform req (`config->platform->php`) however is set to *7.3*, as this is the minimum compatible version that `PHPUnit ^9.5` requires. This is _not_ ideal, and could cause breaking back-compat issues to sneak through …
> chore: set Composer platform reqs

- .changeset/three-ways-dress.md
- includes/utilities/WPHelpers.php
This PR replaces the usage of `rand()` with `wp_rand()` , per the project's PHPCS ruleset.
Since it's anyways being used for a rubbish name property, this should have no actual impact on usage.
> fix: [PHPCS] use `wp_rand()` instead of `rand()`

- .changeset/rude-penguins-develop.md
- .phpcs.xml.dist
This PR disables `phpcs` linting on the `/tests` directory.
WPCS represents WordPress production coding standards. Most of these rules don't apply to the normal PHPUnit (and assumingly future Codeception) patterns, and it seems like unnecessary busywork to ensure they comply with no tangible benefit. It also means contributing tests becomes a `good first issue`, since no knowledge of WordPress/WPGraphQL/WPGraphQLContentBlocks is required.
- We could add a separate `.phpcs.xml.dist` file to the `/tests` directory. This seems unnecessary as per the above.
- We could include them in the default lint, but change `composer phpcs` (and an eventual GH Workflow) to only lint `/includes` and base-directory files. This way the IDE would still hint our ruleset when writing tests, but wouldnt enforce …
> chore: [PHPCS] disable linting on `/tests`

- .changeset/wise-boxes-teach.md
- includes/utilities/DomHelpers.php
This PR replaces the usage of a loose comparator (`==`) with a strict one (`===`), when checking the `$selector` value in `DOMHelpers::parseAttribute()`.
Since there is no loose value that matches `'*'`, this is a code smell that has no effect on the actual plugin logic.
**Note:** The [other use of a loose comparison](https://github.com/wpengine/wp-graphql-content-blocks/blob/946c80f77e666abcd9626cff78d770aacfbb37fc/includes/Data/ContentBlocksResolver.php#L78) picked up by PHPCS has been left alone, since `true == 'true'`)
> fix: [PHPCS] use strict comparison for `$selector`

- includes/Blocks/Block.php
- includes/Type/Scalar/Scalar.php
This PR renames the `WPGraphQL\ContentBlocks\Type\Scalar\Scalar::BlockAttributesObject()` method to the snake_cased `get_block_attributes_object_type_name()` to comply with WPCS while still remaining semantic.
**This is a breaking change.**
As mentioned in #76 , i'd much rather see *this PR rejected* and the codebase replace `Scalar` with:
```php
namespace WPGraphQL\ContentBlocks\Type\Scalar;
class BlockAttributesObject {
public static function register();
public static function get_type_name();
}
```
(since its the same level of 'breaking' for the api), but I'm trying to work within the codebase's existing patterns.
> dev!: rename `BlockAttributesObject()` to `get_block_attributes_object_type_name()`

- .changeset/quiet-boxes-relax.md
- includes/Registry/Registry.php
- includes/Type/Scalar/Scalar.php
- includes/WPGraphQLContentBlocks.php
- tests/unit/RegistryTestCase.php
This PR renames the `WPGraphQL\ContentBlocks\Registry::OnInit()` and the `WPGraphQL\ContentBlocks\Type\Scalar::OnInit()` methods to `::init()` in order to comply with WPCS.
(Personally, I think the entire `Scalar` class should be renamed to `Scalar\BlockAttributesObject` and follow the established ecosystem pattern, but that's a (relatively) larger change with no immediate benefit).
> dev: [PHPCS] rename `OnInit()` methods to `init()`

- .changeset/cuddly-countries-doubt.md
- .changeset/green-bobcats-cover.md
- .changeset/hot-files-jump.md
- .changeset/ten-fishes-breathe.md
- includes/Blocks/Block.php
- includes/Type/InterfaceType/PostTypeBlockInterface.php
- includes/WPGraphQLContentBlocks.php
- includes/utilities/DomHelpers.php
This PR addresses 17 failing PHPCS smells.
While production code has been updated, *no user-facing / api functionality has been changed*. 
- Fixed the usage of `wp-graphql` as a text domain when it should be `wp-graphql-content-blocks`
- Fixed a handful of issues regarding string translation (improper / missing use of `sprintf`, non-escaped strings, unnecessary interpolation).
- Removed the unused params passed from the block attribute field resolver to our anonymous callback.
- Fixed a yoda conditional.
> chore: misc PHPCS fixes

- .changeset/strong-paws-pump.md
- includes/Type/InterfaceType/EditorBlockInterface.php
- tests/unit/EditorBlockInterfaceTest.php
This PR deprecates the unused `$context` param from the `EditorBlockInterface::get_blocks()` method. All internal usage of that method has been updated as well.
Incidentally, the `EditorBlockInterfaceTest` class was also fixed to call that method statically instead of on an instance.
> dev: [PHPCS] deprecate unused `$context` param on `EditorBlockInterface::get_blocks()`

- .changeset/blue-ducks-happen.md
- composer.json
- composer.lock
- readme.txt
- wp-graphql-content-blocks.php
Bumps min required version of PHP to 7.4, to prevent errors like seen in #68. WP would not have allowed the plugin to be activated under those conditions if the plugin header were up to date.
Closes #68
> chore: bump min PHP version to 7.4

- .github/workflows/test-plugin.yml
Removes the fixed 15 second sleep in favor of using `mysqladmin ping` to detect when the db is ready. Seems to save 5-6 secs per run in my tests, and in theory it would prevent failures if mysql took longer than 15 secs.
> ci: wait until db is ready instead of sleeping fixed amount of time

- includes/WPGraphQLContentBlocks.php
Bumps the `WPGRAPHQL_CONTENT_BLOCKS_MIN_PHP_VERSION` to 7.4.
No changeset included, since its the same changelog item at #81
> chore: update `MIN_PHP_VERSION` constant

- .changeset/good-colts-develop.md
- wp-graphql-content-blocks.php
This PR changes the `wpgraphql_content_blocks_init()` method to return `void`.
**Note:** I _do not_ believe this should be considered a breaking change since the only valid use of that method is on `add_action('plugins_loaded')`.
Once merged, PHPStan Level 0 (#87) will pass and a CI workflow can be added to run `phpstan` to prevent the further introduction of Level 0 errors into the codebase.
> fix: [PHPStan] actions should return void

- .changeset/purple-rockets-promise.md
- includes/utilities/DomHelpers.php
This PR fixes a bad conditional in `DOMHelpers::parseFirstNodeAttribute()`, we want to check if the trimmed string is empty, not trim the `bool` check for whether the untrimmed string is empty.
Caught by PHPStan level 5.
> fix: bad conditional check for empty `$html` in `DOMHelpers::parseFirstNodeAttribute()`

- .changeset/few-seas-happen.md
- includes/Blocks/Block.php
- includes/Registry/Registry.php
This PR adds a missing `\` before docblock types using a namespace, as required by by `phpDoc`.
No production code was changed.
Caught by PHPStan level 2.
> chore: [PHPStan] add missing `\` to docblock types

- .changeset/rare-snakes-return.md
- includes/Registry/Registry.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- includes/Type/InterfaceType/PostTypeBlockInterface.php
This PR removes the unused `$type_registry` variable from the `resolveType` callbacks in `EditorPostInterface` and `PostTypeBlockInterface`.
Caught by PHPStan level 1.
**Note:** Technically, `Registry::$type_registry` is now unused and can be removed as well, but IDK what interfaces you have in the docket that may rely on it.
> dev: [PHPStan] remove unused `$type_registry` from `resolveType` callbacks

- .changeset/fair-students-move.md
- includes/utilities/WPHelpers.php
This PR fixes `WPHelpers::get_supported_post_types()`, so it
a) Correctly hints as an array of `WP_Post_Type` objects.
b) Doesn't return void.
The method signature has changed to include a PHP return type, to help prevent future regressions.
Caught by PHPStan level 2.
> fix: [PHPStan] bad return type for `WPHelpers::get_supported_post_types()`

- composer.json
Fixes the `PHP` version constraint, so it allows _any_ PHP version `>=` than 7.4, instead of any **7.x** version greater than 7.4.
I leaked this into the codebase in #70 (It wasn't picked up since it only affects `composer require`-ing the plugin, and not running the plugin itself). As this was the intent of #81 no separate changeset is included.
> fix: Composer PHP version constraint

- .changeset/long-gorillas-rescue.md
- includes/Blocks/Block.php
- includes/Data/ContentBlocksResolver.php
- includes/Field/BlockSupports/Anchor.php
- includes/Registry/Registry.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- includes/Type/Scalar/Scalar.php
- includes/WPGraphQLContentBlocks.php
This PR adds return types to several method signatures.
No actual change in method behavior or expectation has been made.
Caught by PHPStan Level 6
> chore: [PHPStan] add missing return types

- .changeset/chilled-cameras-grin.md
- includes/Data/ContentBlocksResolver.php
This PR fixes several issues in `ContentBlocksResolver::resolve_content_blocks()`, where a lack of type safety could cause a fatal PHP error.
Caught by PHPStan level 8
> fix: [PHPStan] better type checking in `ContentBlocksResolver::resolve_content_blocks()`

- .changeset/poor-books-heal.md
- includes/Registry/Registry.php
- includes/Type/InterfaceType/EditorBlockInterface.php
- includes/Type/InterfaceType/PostTypeBlockInterface.php
- includes/utilities/WPGraphqlHelpers.php
- includes/utilities/WPHelpers.php
This PR refactors `WPGraphQLHelpers::format_type_name()` to better handle empty string / null values, as well as DRYs up the codebase to use it in more places.
This PR **does not** address the _seemingly_ duplicate renaming that entered the codebase in #52 . 
Caught by PHPStan level 6
> fix: [PHPStan] WPGraphQLHelpers::format_type_name() handling

- .changeset/bright-avocados-design.md
- includes/Blocks/Block.php
This PR fixes an issue in `Block::get_block_attributes_field()`, where the method was incorrectly checking if the paramater `$block_attributes` was passed to the method ( `isset()` ) instead of if the value passed was `null`.
The param signature has also been fixed and moved into PHP, to prevent errors like this from going unnoticed in the future.
Caught by PHPStan level 1.
> fix: [PHPStan] `$block_attributes` is always set

- .changeset/gorgeous-horses-arrive.md
- .gitignore
- includes/Data/ContentBlocksResolver.php
- tests/unit/ContentBlocksResolverTest.php
This PR adds support for reusable blocks, rather than simply returning a core/block response. It detects if a reusable block has been found and if so, opens the post and parses the blocks from that, replacing the core/block with the newly parsed blocks.
This is probably a breaking change, given it's no longer sending a core/block response but it would equally be breaking if the core/block was mutated to embed the blocks within innerBlocks or similar. This in my opinion is the most compatible approach, it allows the reusable blocks to simply appear as if they were non-reusable from the GQL response perspective - allowing end users to change from reusable <> non-reusable with zero difference in the GQL response output - which feels sensible from my perspective.
> Add support for reusable blocks

- .changeset/great-ravens-joke.md
- includes/Blocks/Block.php
- includes/Field/BlockSupports/Anchor.php
- includes/Registry/Registry.php
Fixes #98.
The interface was being registered for any block that supported anchors, if more than one block supported them then GraphQL was complaining about duplicate entries. This moves the registering of the interface to the registry and then the application of that interface within the block registering flow only registers that interface to the type/block.
> Only register the anchor once, then apply to the block

- includes/Blocks/CoreSeparator.php
Adds cssClassName attribute in CoreSeparator
Check that the `cssClassName` attribute is available in the CoreSeparator block.
> Feat: Add CoreSeparator cssClassNames

- .changeset/curly-spiders-greet.md
- includes/Blocks/CoreHeading.php
Adds a new field for providing the css class for a CoreHeading block.
1 Create a CoreHeading block.
2 Query the `cssClassName` attribute. It should extract the class Names of the heading element and it should match the css of the rendered HTML content.
> Feat: Add CoreHeading css classNames

- .changeset/new-planes-itch.md
- includes/Blocks/CoreList.php
Adds the `cssClassName` attribute to the `CoreList` block similar to https://github.com/wpengine/wp-graphql-content-blocks/pull/122
1. Create a `CoreList` block on a page or post
2. Query for that page/post in WPGraphQL GraphiQL
3. Query the `cssClassName` attribute on the `CoreList` block
4. Notice the class names come back as expected
> Add `cssClassName` to CoreList block

- .changeset/serious-items-bow.md
- includes/Blocks/CoreImage.php
- tests/unit/blocks/CoreImageTest.php
Fixed bug when CoreImage width attribute fails to resolve thowing error.
1 - Perform a query on the width attributes of the `CoreImage` and `CoreColumn` Blocks using fragments. You can look at the test case query for example.
2 - Query fails with the following error:
Fields \"attributes\" conflict because subfields \"width\" conflict because they return conflicting types Float and String.
Afte the fix this should resolve without issues.
> Bug: CoreImage width attribute resolve throws error.

- .docker/Dockerfile
- .github/workflows/schema-linter.yml
- .github/workflows/test-plugin.yml
- docker-compose.yml
Description
---
Add GH actions matrix to run unit tests  against the following combinations of php, WP and MySQL
php: [ '8.2', '7.4' ]
WordPress: [ '6.2', '6.1', '5.9' ]
mySql: 8.0
Excluded: Docker images for  WordPress v5.9 and php v8.2 are not available.
> CI/CD: Run tests against php8.2+mysql8.0

- .changeset/spicy-tables-cross.md
- includes/Blocks/Block.php
- tests/unit/blocks/CoreVideoTest.php
Bug fix. Parsing boolean block attributes like in CoreVideo always return false. 
Fixes: https://github.com/wpengine/wp-graphql-content-blocks/issues/135
1. Add a CoreVideo block in a Post and enable some of its checkbox settings for autoplay on the side.
2. Try to query the block attributes.
3. The boolean attributes should return the correct checked/unchecked value.
> Bug Fix: Parsing boolean block attributes like in CoreVideo always return false.

- .changeset/thin-insects-sparkle.md
- includes/Blocks/Block.php
- includes/Field/BlockSupports/Anchor.php
- includes/Registry/Registry.php
* Removed usage of `register_graphql_interfaces` to_types in `register_block_types`
* Related [Comment](https://github.com/wpengine/wp-graphql-content-blocks/issues/134#issuecomment-1652113161)
* Populated WP site with 100 Posts and 100 Pages.
* Using [autocannon.js](https://github.com/mcollina/autocannon
) script:
```js
const autocannon = require("autocannon");
const instance = autocannon(
{
url: "http://mysite.local",
connections: 12,
pipelining: 1,
duration: 30,
headers: {
accept: "application/json",
"accept-language": "en-GB,en;q=0.9,de;q=0.8,el;q=0.7,en-US;q=0.6",
"cache-control": "no-cache",
"content-type": "application/json",
pragma: "no-cache",
Referer: "http://mysite.local/wp-admin/admin.php?page=graphiql-ide",
"Referrer-Policy": "strict-origin-when-cross-origin",
},
requests: [ …
```
> Refactor: (Performance) `register_graphql_interfaces` no longer used in `register_block_types`

- .changeset/calm-taxis-speak.md
- includes/Registry/Registry.php
This adds a filter to the `get_block_context_interfaces` method, allowing 3rd party code to opt-out of ${PostTypeName}EditorBlock Interface(s) from being implemented to a block. 
closes #147
> feat: add filter to `get_block_context_interfaces()`

- .changeset/odd-files-attend.md
- includes/Utilities/WPHelpers.php
- tests/unit/RegistryTestCase.php
Replaces the `post_type_supports` with `use_block_editor_for_post_type` when resolving the `get_supported_post_types`. This has the added benefit of running the [use_block_editor_for_post_type](https://developer.wordpress.org/reference/hooks/use_block_editor_for_post_type/) hook that was missed, potentially including blocks that dont work with the block editor. 
Closes #27
> [Merl-786] `post_type_supports` -> `use_block_editor_for_post_type`

- readme.txt
I tested our wp-graphql-content-blocks plugin with the [WordPress Beta Tester](https://wordpress.org/extend/plugins/wordpress-beta-tester/) plugin. After uploading this testing plugin, I changed the settings of the plugin to the following to enable v6.4 testing: 
I then updated WordPress to version 6.4-RC3:
Upon installation of version 6.4-RC3, I pulled up my testing repo, which contains blocks from our blockset command example project, as well as my own customized block. I tested the customized block with the GraphiQL IDE and am still able to perform queries for the block data:
I examined customized blocks in the editor and on the site previews and noticed that the initial publishing of blocks resulted in the correct display of the blocks on the site:
Editor: 
Site: 
However, previews is …
> Updated readme.txt version with 6.4

- .changeset/ten-dolphins-smash.md
- includes/Blocks/Block.php
- includes/Data/ContentBlocksResolver.php
- includes/Type/Scalar/Scalar.php
- includes/Utilities/DomHelpers.php
- tests/unit/blocks/CoreTableTest.php
- tests/unit/blocks/CoreVideoTest.php
Fixes: https://github.com/wpengine/wp-graphql-content-blocks/issues/61
* Create a Table Block and add a header footer and caption
* Add also some cells
* You will be able to query the head, foot and content cells
> Add support for querying array type query data from blocks

- .changeset/spotty-nails-complain.md
- includes/Blocks/CoreCode.php
- includes/Blocks/CoreParagraph.php
Adds a missing `default` value for the `CoreParagraph` and `CoreCode`  `content` fields.
- Go to the GraphQL inspector and Search for the `CoreParagraphAttributes` type. It should be of type `String!` instead of `String`.
- Go to the GraphQL inspector and Search for the `CoreCodeAttributes` type. It should be of type `String!` instead of `String`.
> Fix paragraph content default attribute

- .changeset/soft-teachers-protect.md
- includes/Blocks/Block.php
This is a Regression bug fix caused by [this PR](https://github.com/wpengine/wp-graphql-content-blocks/pull/176). 
`parseAttribute` would use the wrong default value and thus would return a wrong type for GraphQL which would cause 500 errors.
This PR fixes that issue.
1. Use the following post content structure:
2. Try to perform a full query of this page using the following query:
```
fragment CoreParagraphBlockFragment on CoreParagraph {
attributes {
cssClassName
backgroundColor
content
style
textColor
fontSize
fontFamily
direction
dropCap
gradient
align
}
}
fragment CoreColumnsBlockFragment on CoreColumns {
attributes {
align
anchor
layout
cssClassName
isStackedOnMobile
verticalAlignment
borderColor
backgroundColor
fontSize
fontFamily
style
textColor
gradient
}
}
fragment …
```
> Bug Fix: parseAttribute function uses wrong default value.

- .changeset/clean-crews-draw.md
- composer.json
- composer.lock
This pr removes `squizlabs/php_codesniffer` from our composer.json. 
No other dependencies have been updated.
It is unnecessary as it is already included by VIPCS (wia wp-graphql-cs).
Closes #199
> chore: remove `squizlabs/php_codesniffer` from Composer's direct dependencies

- readme.txt
[Internal logistics tracking](https://github.com/orgs/wpengine/projects/13/views/1?pane=issue&itemId=56809132) 
I tested our plugin with the [WordPress Beta Tester](https://wordpress.org/extend/plugins/wordpress-beta-tester/) plugin. After uploading this testing plugin, I changed the settings of the plugin to the following to enable v6.5 testing: 
I then updated WordPress to version 6.5-RC3:
I then headed over to the GraphiQL IDE to test the functionality of the blocks. I am still able to perform queries for the block data, and posts still function normally.
> Changed 'tested up to' in readme.txt to 6.5

- .changeset/popular-gifts-shop.md
- phpstan-baseline.neon
- phpstan.neon.dist
This PR bumps the PHPStan ruleset to level 8, while adding a baseline to ignore existing PHP errors.
It seems my previous PRs around code quality were too aspirational. By bumping the ruleset now we can prevent the introduction of even more PHP errors into the codebase, while providing a clear to-do list for the existing errors that need to be addressed.
> chore: bump PHPStan to level 8 and generate baseline.

- .changeset/tough-jokes-turn.md
- phpstan-baseline.neon
- phpstan.neon.dist
- phpstan/class-wp-post-type.php
- phpstan/constants.php
This PR
- Stubs `WP_Post_Type` so the custom GraphQL properties are available in PHPStan (and our IDEs)
- Includes `wp-graphql-content-blocks.php` in PHPStan's bootstrapper, to correctly identify the defined constants.
The PHPStan baseline has been updated accordingly.
Address false positives and uncover more _actual_ tech debt.
> chore: stub WP_Post_Type and boostrap main plugin file during phpstan

- .changeset/quick-maps-exercise.md
- .changeset/tough-jokes-turn.md
- includes/Data/ContentBlocksResolver.php
- phpstan-baseline.neon
- phpstan.neon.dist
- phpstan/class-wp-post-type.php
- phpstan/constants.php
This PR fixes a PHP error where we were directly trying to access `post_content` on `get_post()` without verifying that an actual post is returned.
The logic has been changed to check if `$post->post_content` is empty, also saving us a call to `parse_blocks` if the post exists, but has no content.
> [!Warning]
> This PR requires #210 , which should be merged first (to avoid conflicts with the PHPStan baseline). The diff of specific changes is viewable here: a7aea08a1629ebbf8056e340f06a7d621babe42b
> fix: check `post_content` before parsing it for blocks

- .changeset/neat-ties-prove.md
- includes/Registry/Registry.php
- phpstan-baseline.neon
This PR changes the param type of `$supported_blocks_for_post_type_context` (used in `wpgraphql_content_blocks_should_apply_post_type_editor_blocks_interfaces` ) to type `array|bool`
> [!WARNING]
> ~This PR requires https://github.com/wpengine/wp-graphql-content-blocks/pull/210 , which should be merged first (to avoid conflicts with the PHPStan baseline). The diff of specific changes is viewable here: b5122b93f10535d4719086edc555a39f1625c21c~
`get_allow_block_types()` [can return a boolean](https://developer.wordpress.org/reference/functions/get_allowed_block_types/) when all block types are enabled/disabled
> fix: `get_allowed_block_types()` can return `bool`

- .changeset/wild-hairs-jog.md
- includes/Utilities/DomHelpers.php
- phpstan.neon.dist
- phpstan/constants.php
This PR updates `phpstan.neon.dist` for stricter detection of errors, and addresses the newly-detected errors. More specifically:
- Calls to `DiDom\Document::loadHtml()` have been updated to use the correct casing. (Previously these were calls to `loadHTML()`)
- Removes `null` from the return DocType of DOMHelpers::getElementsFromHTML() and DOMHelpers::parseHTML(), since those methods only turn a type `string` IRL. Note: The method signature **was not** changed.
> [!WARNING]
> ~This PR requires https://github.com/wpengine/wp-graphql-content-blocks/pull/210 , which should be merged first (to avoid conflicts with the PHPStan baseline). The relevant commits for this PR are:~
> ~- b7109ac14c46552e6e52321084170a5b892ed0d2~
> ~- 4308eafb13bdfe727ec164e876891ae1e28e2f30~
> ~- …
> chore: implement stricter PHPStan ruleset and fix new errors.

- .changeset/loud-carpets-dress.md
- composer.lock
- includes/Blocks/Block.php
This PR updates the composer dev-deps (including transitive dependencies) to their latest (SemVer compatibile) versions, and then runs `phpcs:fix` to autofix the newly addressed smells.
**No production code has been changed**
Includes latest versions of WPCS and PHPStan, so I dont have to redo these code-quality PRs.
> chore: update Composer dev-deps and lint

- .changeset/unlucky-deers-remain.md
- includes/Registry/Registry.php
- phpstan-baseline.neon
This PR filters the supported Post Type graphql names for null values, before attempting to register the `NodeWithEditorBlocks` interface to them.
`register_graphql_interfaces_to_types()` takes an array of `string` values, not `array<string|null>`.
> [!IMPORTANT]
> At this stage, we're likely going to start seeing merge conflicts on `phpstan-baseline.neon`, due to multiple lines getting deleted at the source.
>
> To resolve without waiting for @justlevine , restore the base (i.e. `main` branch) `phpstan-baseline.neon` file, and then reapply the removal of the specific allow-listed error from the `phpstan-baseline.neon` diff in this PR.
> fix: Don't register `NodeWithEditorBlocks` interface to `null` type names

- .changeset/selfish-rockets-allow.md
- includes/Field/BlockSupports/Anchor.php
- phpstan-baseline.neon
This PR removes the unnecessary `isset( $block_spec )` check from the guard in `Anchor::get_block_interfaces()`
`$block_spec` is strictly-typed to `WP_Block_Type`, and therefore `isset()` will always be true.
> [!IMPORTANT]
> At this stage, we're likely going to start seeing merge conflicts on `phpstan-baseline.neon`, due to multiple lines getting deleted at the source.
>
> To resolve without waiting for @justlevine , restore the base (i.e. `main` branch) `phpstan-baseline.neon` file, and then reapply the removal of the specific allow-listed error from the `phpstan-baseline.neon` diff in this PR.
> chore: remove unnecessary `isset()` in `Anchor::get_block_interfaces()`

- .changeset/serious-numbers-chew.md
- includes/Blocks/Block.php
- phpstan-baseline.neon
This PR:
- removes the `Block::resolve()` method, and instead inlines the `name` field resolver logic in `register_graphql_object_type()` $config.
- changes the `name` field resolver logic to return `null` if `$source['blockName']` is unset, instead of an empty string.
As the method is private, and the schema for the `name` field already being nullable, this is _not_ a breaking change.
Prompted by the lack of return type on `Block::resolve()`, I noted it's a private method (i.e. not overloadable by child classes), used only inside another private method `Block::register_type()`.  Removing the type both cleans up the tech debt, and makes it clearer to see what changes would be necessary to actually make `Block` and overloadable class.
> [!IMPORTANT]
> At this stage, we're likely going to …
> dev: inline and remove `Block::resolve()` and make `name` field nullable

- .changeset/shaggy-walls-rush.md
- includes/Registry/Registry.php
- phpstan-baseline.neon
This PR fixes the calls to in `Registry::get_block_additional_interfaces()` and `Registry::get_block_attributes_interfaces()` to ensure that the `$block_spec` is a valid `WP_Block_Type` before trying to apply an `Anchor` interface to it.
Both `Anchor::get_block_attributes_interfaces()` and `Anchor::get_block_interfaces()` require `$block_spec` to be a valid `WP_Block_Type`.
While the pattern for applying the Anchor Interfaces could be improved, that's beyond the scope of this PR.
> [!IMPORTANT]
> At this stage, we're likely going to start seeing merge conflicts on `phpstan-baseline.neon`, due to multiple lines getting deleted at the source.
>
> To resolve without waiting for @justlevine , restore the base (i.e. `main` branch) `phpstan-baseline.neon` file, and then reapply the removal of …
> fix: ensure valid `WP_Block_Type` before applying `Anchor` interfaces.

- .changeset/great-pans-poke.md
- includes/Blocks/Block.php
- phpstan-baseline.neon
This PR changes the `$prefix` parameter on `Blocks::get_block_attribute_fields()` from a nullable string (`string|null`) to a non-nullable `string`. The parameter remains optional and defaults to `''`.
>[!NOTE]
> This is _not_ considered a breaking change as `get_block_attribute_fields()` is a `private` class method, and [its only usage](https://github.com/justlevine/wp-graphql-content-blocks/blob/55fc5dc82a4bcaa4d4b8d78c286ca2306f66742d/includes/Blocks/Block.php#L90) has it passed a `string` value.
`Blocks::get_block_attribute_fields()` passes the `$prefix` param to `Blocks::get_attribute_type()` which requires the param to be a non-nullable string.
> [!IMPORTANT]
> At this stage, we're likely going to start seeing merge conflicts on `phpstan-baseline.neon`, due to multiple lines getting …
> fix: make `get_block_attribute_fields()` `$prefix` param non-nullable

- .github/workflows/upload-schema-artifact.yml
This attempts to fix #197 by only running the schema generator on tag. The assumption is that the release workflow creates the tagged release itself so the release will be present and capable of receiving the upload.
Note that while this was tested in a fork of this repo, a lot of assumptions were made that prevented a full workflow from triggering. This can be further tested here by disabling the CircleCI runs and a willingness to delete extra releases from this repo.
> Only attempt to update schema on release tags

- .changeset/tame-baboons-juggle.md
- includes/Blocks/Block.php
- includes/Utilities/DOMHelpers.php
- phpstan-baseline.neon
This PR renames the `DomHelpers.php` file to `DOMHelpers.php` to match the class-name casing, per PSR-4.
Additionally, it fixes the internal and return types for the DomHelpers methods, and their usage.
`DiDom` methods have the ability to return either a `DiDom\Element` or a `DOMElement` instance depending on the supplied parameters. By explicitly typing those instances, we're able to unearth actual issues with the methods (like DOMHelpers::findNodes() returning `null` or being used as an array when it returns a single element.
- The use of `DOMHelpers::findNodes()` in [Block::parse_single_source()](https://github.com/justlevine/wp-graphql-content-blocks/blob/e70bd1f014904eeb39d06134048f9024391b3141/includes/Blocks/Block.php#L457) is _not addressed_ in this PR. We probably want to be …
> fix: rename `DomHelpers.php` to `DOMHelpers.php` and improve type-safety of internal methods.

- .changeset/good-poems-battle.md
- includes/Blocks/Block.php
- phpstan-baseline.neon
This PR fixes the logic inside `Block::normalize_attribute_values()` to:
- return `array` values before casting to the normalized `type`.
- cast strings to an array if the `$type` is an array, but the `$value` is not.
**No effort has been made** to determine the possible Scalar types that `$value` can accept, and instead is assumed to only be a `string|array` as currently defined in the doc-block.
You can't cast arrays to strings in PHP.
> [!IMPORTANT]
> At this stage, we're likely going to start seeing merge conflicts on `phpstan-baseline.neon`, due to multiple lines getting deleted at the source.
>
> To resolve without waiting for @justlevine , restore the base (i.e. `main` branch) `phpstan-baseline.neon` file, and then reapply the removal of the specific allow-listed error from the …
> fix: handle arrays before casting when normalizing attribute values

- .changeset/famous-hats-deliver.md
- includes/Blocks/Block.php
- includes/Blocks/CoreCode.php
- includes/Blocks/CoreParagraph.php
MAJOR: Update Schema to reflect latest WordPress 6.5 changes.
- **WHAT the breaking change is:** Added a new `rich-text` type.
- **WHY the change was made:** WordPress 6.5 replaced some of the attribute types from string to `rich-text` causing breaking changes to the existing block fields.
- **HOW a consumer should update their code:** If users need to use WordPress >= 6.5 they need to update this plugin to the latest version and update their graphql schemas.
https://github.com/wpengine/wp-graphql-content-blocks/issues/225
-Update to WordPress 6.5
- Add a post with some paragraphs, code and heading blocks
- When querying their `content` attributes, there should be no issues or graphql errors.
> Breaking Update: Handle `rich-text` field for WordPress >= v6.5

- .github/workflows/test-plugin.yml
Adds WordPress 6.4 and 6.5 to the testing matrix.
Note the "draft" status of this PR will be removed upon release of the official WordPress 6.5 Docker image.
> chore: add WordPress 6.4 and 6.5 to testing matrix

- .github/workflows/upload-schema-artifact.yml
This abandons the tag push which, upon research, isn't triggered due to how the release action tags the release itself.
Instead of relying on the tag, it moves to the `release` trigger in an attempt to run when a release is published.
In testing on a personal repo the trigger is fired successfully. A test here won't be possible until we try a fresh release.
> Use "release" trigger for running the upload schema workflow.

- .github/workflows/phpstan.yml
- composer.json
This PR runs PHPStan as part of the CI workflow on pull requests.
Prevent regressions in static analysis.
> ci: add PHPStan workflow

- .changeset/wild-seas-buy.md
- includes/Type/InterfaceType/PostTypeBlockInterface.php
This PR removes the unnecessary `flat` arg definition from `NodeWith{$Post_Type}EditorBlocks`, instead relying on the arg definition set by the parent `NodeWithEditorBlocks`.
The _real_ reason is that there is no difference between the parent and child implementations, so there's no reason to overload.
The superficial reason is that it works around a WPGraphQL core regression https://github.com/wp-graphql/wp-graphql/pull/3152 which:
- closes #240 
- fixes the missing argument description error in `graphql-schema-linter`.
Look ma no `extension.debug` messages
> fix: dont overload `NodeWithEditorBlocks.flat`

- .changeset/weak-knives-brush.md
- includes/Blocks/Block.php
This PR refactors `Block::resolve_block_attributes_recursive()` in the following ways:
1. Add types to the method signature _when the types are certain_.
2. Breaks out source parsing into individual methods, for reduced code complexity.
3. Checks for array keys before they are used on the array:
- On required `$value` keys that are necessary to parse the source.
- Before post-processing the `$return[ $key ]` values retrieved from the source.
Prevents `Undefined array key` PHP warnings, as well as improves handling of malformed blocks.
Fixes #238
> fix: undefined array keys in `Block::resolve_block_attributes_recursive()`

- .changeset/sweet-jars-shout.md
- includes/Data/ContentBlocksResolver.php
- includes/Utilities/TraverseHelpers.php
- tests/unit/ContentBlocksResolverTest.php
- tests/unit/TraverseHelpersTest.php
Fixes https://github.com/wpengine/wp-graphql-content-blocks/issues/184
> fix: reusable block isn't resolved inside inner blocks

- .changeset/cuddly-yaks-try.md
- composer.lock
- includes/Blocks/Block.php
- includes/Utilities/TraverseHelpers.php
- includes/WPGraphQLContentBlocks.php
- phpstan.neon.dist
This PR updates the Composer dev-dependencies to their latest versions, and fixes the newly exposed PHPCS/PHPStan smells.
Got a bunch of incoming PRs lined up, and want to use accurate tooling.
The only production-code change in this PR is fixing the recursive use of `Block::get_attribute_type()` from static to instance, since it's registered as a private instance method on the class.
> chore: update Composer dev-dependencies and fix resulting issues.

- .changeset/green-baboons-double.md
- .github/workflows/test-plugin-nightly.yml
- .github/workflows/test-plugin.yml
This PR replaces all instances of the outdated `docker-compose` command with the current syntax: `docker compose`
Havn't seen an article yet, but seems like GH runners dropped compatibility with the old command: https://github.com/wpengine/wp-graphql-content-blocks/actions/runs/10094219877/job/28273101015?pr=257
> ci: replace `docker-compose` commands with `docker compose`

- README.md
These changes update the broken readme badge to point to an existing test
> docs: Update README badge

- .changeset/large-cheetahs-flow.md
- includes/Data/ContentBlocksResolver.php
This PR adds the `wpgraphql_content_blocks_pre_resolve_blocks` and `wpgraphql_content_blocks_resolve_blocks` filters to `ContentBlocksResolver::resolve_content_blocks()`.
Beyond the general DX arguments, this allows local workarounds for the existing bugs without waiting for upstream patches by an understaffed team.
- If `wpgraphql_content_blocks_pre_resolve_blocks` returns anything but `null`, the results will be used instead. This is good for swapping out the entire resolver's results without resulting to a messy resolver overloading or forking.
- `wpgraphql_content_blocks_resolve_blocks` is used to filter the blocks _after_ the `::resolve_content_blocks()` method processes them. This is good for hydrating missing values that the plugin doesnt handle currently/WP 6.5+ regressions.
> dev: add filters to `resolve_content_blocks()`

- .changeset/light-frogs-grow.md
- .github/workflows/test-plugin-nightly.yml
- .github/workflows/test-plugin.yml
- docker-compose.yml
- readme.txt
This PR explicitly tests the plugin against WP 6.6.x and bumps the readme.txt headers to 6.6.2
> chore: test against WP 6.6

- .changeset/late-poems-study.md
- includes/updates/update-callbacks.php
- phpstan-baseline.neon
- phpstan/constants.php
This PR remediates several PHPStan errors, caused solely by PHPStan's configuration, and in one case an incorrect docblock annotation.
**No code has been changed in this PR**
> chore: fix non-code phpstan errors

- .changeset/green-cows-accept.md
- includes/updates/update-callbacks.php
- phpstan-baseline.neon
This PR fixes the usage of `get_current_screen()` to check if it's set, before attempting to access properties.
It can cause a fatal php error. Personally, it's getting in the way of my unit tests.
```php
<?php
// functions.php
do_action( 'admin_notices' );
```
If it doesnt error, it worked. Or just run `composer phpstan` and confirm it's passing even though the ignore rule has been removed from the baseline.
> fix: check if `get_current_screen()` is set before accessing properties

- .changeset/little-cobras-admire.md
- tests/unit/BlockSupportsAnchorTest.php
- tests/unit/EditorBlockInterfaceTest.php
- tests/unit/PostTypeBlockInterfaceTest.php
- tests/unit/RegistryTestCase.php
This PR fixes deprecation warnings in several PHPUnit tests caused by accessing an undefined `get_option('graphql_general_settings')`.
> [!IMPORTANT]
> This PR is based on https://github.com/wpengine/wp-graphql-content-blocks/pull/280 and requires it to be merged first
The deprecated warnings were being shown on running the `composer tests`.
- Ensure `$settings` is an array before updating one of it's values.
Before :
No more deprecation warnings ✅
> tests: fix PHP deprecated notice - Automatic conversion of false to array

- .changeset/ten-bulldogs-cover.md
- includes/Type/InterfaceType/EditorBlockInterface.php
- includes/Type/InterfaceType/PostTypeBlockInterface.php
- includes/Utilities/WPGraphQLHelpers.php
- tests/unit/EditorBlockInterfaceTest.php
- tests/unit/PostTypeBlockInterfaceTest.php
This PR adds the `type` field to the `EditorBlock` interface.
Many block implementations (including Faust) rely on using the block type to match the component. Currently, the only way to do that is enable public introspection for the entire GraphQL server, and use `__typename`. By adding a `type` field, we can do that mapping without public introspection.
A new `WPGraphQLHelpers::get_type_name_for_block()` method has been introduced to keep the code DRY. It's been marked `@internal` to discourage usage (since once we have a Block model, we can _just_ define the `type` and use `$block->type` to resolve the interface).
> feat: expose `EditorBlock.type` field

- .changeset/odd-pens-rule.md
- .changeset/spotty-files-own.md
- includes/Blocks/Block.php
- includes/Data/BlockAttributeResolver.php
- includes/Data/ContentBlocksResolver.php
- phpstan-baseline.neon
This PR adds support for attributes with a [`meta` source](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/block-api/block-attributes.md#meta-source-deprecated).
> [!IMPORTANT]
> This PR is based on #284 , which should be merged first. 
>
> Relevant diff: https://github.com/wpengine/wp-graphql-content-blocks/pull/286/commits/0f3010ceeb1b6d6a6055b6ec3ebedb25db0f1533
Although `meta` is considered deprecated, many third-party and legacy blocks still rely on in.
Tests will be backfilled alongside other ongoing work as they require mocking a custom block with a meta field.
> feat: parse `meta` attributes

- .changeset/dull-pandas-joke.md
- tests/unit/AutoloaderTest.php
- tests/unit/BlockAttributesObjectTest.php
- tests/unit/BlockQueriesTest.php
- tests/unit/BlockSupportsAnchorTest.php
- tests/unit/ContentBlocksResolverTest.php
- tests/unit/CoreImageTest.php
- tests/unit/CoreTableTest.php
- tests/unit/CoreVideoTest.php
- tests/unit/EditorBlockInterfaceTest.php
- tests/unit/PostTypeBlockInterfaceTest.php
- tests/unit/RegistryTestCase.php
- tests/unit/UpdateCallbacksTest.php
This PR fixes the `::setUp()` and `::tearDown()` methods in our PHPUnit test classes. More specifically
- The WPGraphQL schema is cleared between each test.
- Our local tear-downs occur _before_ `parent::tearDown()`
- We now delete options in `::tearDown()` that were created in `::setUp()`
- Removed unnecessary `$wpdb` calls.
**As a result, `markTestSkipped()` has been removed from `CoreTableTest` and `CoreVideoTest` since they're no longer necessary.**
Additionally, the class namespace was added to `UpdateCallbacksTest.php` since the autoload error was bothering me.
`CoreImageTest` is for some reason what's causing `CoreTableTest` etc to skip their `attributes` registration, and clearing the WPGraphQL schema allows it to work again.
Made sense to apply it for equal measure, since the …
> tests: fix `setUp()`/`tearDown()` methods

- .changeset/fair-scissors-teach.md
- tests/unit/CoreImageTest.php
This PR backfills tests for the `Core Image` block and its attributes.
- id
- width
- height
- alt
- align
- aspectRatio
- src
- style
- scale
- sizeSlug
- lightbox
- linkClass
- linkTarget
- linkDestination
- borderColor
- caption
- className
- cssClassName
- url
- rel
- href
- title
- lock
- anchor
- `CoreImageAttribute.metadata` - @todo
NA
> test : Add tests for Core Image Block

- .changeset/good-days-work.md
- tests/unit/CoreVideoTest.php
This PR backfills tests for the `Core Video` block and its attributes.
- align
- anchor
- autoplay
- muted
- caption
- className
- preload
- src
- style
- playsInline
- controls
- loop
- lock
- poster
- tracks
- id
- `CoreVideoAttribute.metadata` - @todo
NA
> tests : backfill tests for `Core Video` Block

- .changeset/silver-actors-retire.md
- tests/unit/CoreCodeTest.php
This PR adds comprehensive tests for the `CoreCode` block and its attributes.
- align
- anchor
- borderColor
- className
- content
- cssClassName
- fontFamily
- fontSize
- gradient
- lock
- style
- textColor
- `CoreCodeAttributes.metadata` - @todo
- None identified during testing. All attributes appear to be correctly implemented and returned as expected.
> tests: Add tests for `CoreCode` Block

- .changeset/orange-buses-help.md
- tests/unit/CorePreformattedTest.php
This PR adds comprehensive tests for the `CorePreformatted` block and its attributes.
- anchor
- className
- content
- fontFamily
- fontSize
- gradient
- lock
- style
- textColor
- - `CorePreformattedAttributes.metadata` - @todo
- None identified during testing. All attributes appear to be correctly implemented and returned as expected.
> tests: Add tests for `CorePreformatted` Block

- .changeset/olive-clocks-clean.md
- tests/unit/CoreParagraphTest.php
This PR adds comprehensive tests for the `CoreParagraph` block and its attributes.
- align
- anchor
- className
- content
- cssClassName
- dropCap
- direction
- fontFamily
- fontSize
- gradient
- lock
- placeholder
- style
- textColor
- `CoreParagraphAttributes.metadata` - @todo
- None identified during testing. All attributes appear to be correctly implemented and returned as expected.
> tests: Add tests for `CoreParagraph` block

- .changeset/thirty-chicken-drum.md
- tests/unit/CoreQuoteTest.php
This PR backfills tests for the `Core Quote` block and its attributes.
- anchor
- citation
- className
- cssClassName
- fontFamily
- fontSize
- gradient
- layout
- lock
- style
- textAlign
- textColor
- value
- `CoreQuoteAttributes.metadata` - @todo
NA
> tests : Add tests for `Core Quote` block.

- .changeset/odd-hounds-sing.md
- tests/unit/CoreSeparatorTest.php
This PR backfills tests for the `CoreSeparator` block and its attributes.
- align
- anchor
- className
- cssClassName
- gradient
- lock
- opacity
- style
- `CoreSeparatorAttributes.metadata` - @todo
NA
> tests : Add tests for `CoreSeparator` block. 

- .changeset/weak-days-suffer.md
- tests/unit/ContentBlocksResolverTest.php
This PR backfills additional test cases for the `ContentBlocksResolver` class in `ContentBlocksResolverTest`.
The following test cases are included:   
- **Pre-resolve Filter Test:** `test_pre_resolved_blocks_filter_returns_non_null` ensures that the `wpgraphql_content_blocks_pre_resolve_blocks` filter correctly modifies the block content before the blocks are resolved.
- **Empty Content Test:** `test_returns_empty_array_for_empty_content` checks that an empty array is returned when the post content is empty, ensuring proper behavior for posts with no blocks.
- **Post-resolve Filter Test:** `test_filters_wpgraphql_content_blocks_resolve_blocks` ensures that the `wpgraphql_content_blocks_resolve_blocks` filter correctly modifies block content after the blocks are resolved.
- **Inner Block …
> tests: backfill tests for `ContentBlockResolver`

- .changeset/silly-poems-happen.md
- wp-graphql-content-blocks.php
This was corrected by running node ./bin/versionPlugin.js
> fix: incorrect plugin version

- .changeset/thin-donuts-float.md
- includes/Type/InterfaceType/EditorBlockInterface.php
- tests/unit/BlockQueriesTest.php
- tests/unit/BlockSupportsAnchorTest.php
- tests/unit/CoreCodeTest.php
- tests/unit/CoreHeadingTest.php
- tests/unit/CoreImageTest.php
- tests/unit/CoreListTest.php
- tests/unit/CoreParagraphTest.php
- tests/unit/CorePreformattedTest.php
- tests/unit/CoreQuoteTest.php
- tests/unit/CoreSeparatorTest.php
- tests/unit/CoreTableTest.php
- tests/unit/CoreVideoTest.php
This PR fixes a regression in #285 where the `type` field was exposed with no resolve method, cause the field to always return null.
In the upstream branch I'm hydrating blocks with a model, but we need an explicit resolve function until that's merged.
> fix: Ensure correct `EditorBlock.type` field resolution

- .github/workflows/test-plugin-nightly.yml
- .github/workflows/test-plugin.yml
- readme.txt
This PR bumps the `Tested up to` header and various CI variables to WordPress `6.7`.
> ci: test against WordPress 6.7

- .changeset/tiny-news-warn.md
- includes/Data/ContentBlocksResolver.php
- tests/unit/ContentBlocksResolverTest.php
This PR adds support to resolving the `innerBlocks` for synced Block Patterns, introduced in WordPress 6.6
While synced patterns are a highlight of FSE, they are still commonly inserted manually into post/page/cpt content, especially in hybrid themes.
Since this is a backwards-compatible improvement, I believe it makes sense to introduce this now instead of after any incoming breaking changes.
See diff
> feat: add support for resolving pattern blocks

- .changeset/itchy-mugs-sniff.md
- includes/Data/ContentBlocksResolver.php
- tests/unit/ContentBlocksResolverTest.php
This PR adds support for resolving `innerBlocks` for `core/post-content` blocks.
> [!IMPORTANT]
> This PR is based off of https://github.com/wpengine/wp-graphql-content-blocks/pull/324, which should be merged first.
> Relevant diff: 8e2e921850d709092e6f051f88d7d5a9d239841b
This is _essential_ for supporting FSE, and due to the `final`/`private` nature of `ContentBlocksResolver` cannot be easily hooked in from external code.
While the WPGraphQL core does not (yet) support querying for a complete FSE template (where `core/post-content` is traditionally used, I believe the above consideration along with the following reasons still make this a good candidate for inclusion:
1. While an unlikely edge case, the fact that it's replicable in the tests using public hooks and functions means it not …
> feat: add support for resolving PostContent blocks

- .changeset/proud-fireants-buy.md
- includes/Blocks/CoreGroup.php
- tests/unit/CoreGroupTest.php
This adds the cssClassName for the CoreGroupAttributes as per issue reported here #327 
See above.
#327 
The following test checks that cssClassName is availble for the CoreGroupAttributes
If you update a page with the following HTML
```
<header id="test-group-id" class="wp-block-group test-group-class is-style-section-1 has-border-color has-accent-3-border-color has-accent-3-color has-base-background-color has-text-color has-background has-link-color" style="border-width:4px;border-radius:1px;min-height:100px;margin-top:var(--wp--preset--spacing--20);margin-bottom:var(--wp--preset--spacing--20);padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--20)">
<p>This is the …
```
> feat: Added cssClassName attribute to CoreGroup

- .changeset/bright-trains-approve.md
- readme.txt
See  #263
WP GraphQL is now a plugin requirement.
> Added WP GraphQL as a plugin requirement.

- .changeset/calm-socks-battle.md
- includes/Blocks/CorePostTerms.php
- tests/unit/CorePostTermsTest.php
Related issue: #180 
- Adds terms querying functionality for the CorePostTerms Block.
New `terms` ~~field~~ **connection** registered. ~~Resolves as a list_of TermNode~~
New `taxonomy` connection registered.
- Additionally adds support for the `prefix` and `suffix` items with correspondent newly registered string fields.
```graphql
query TestPostTerms($uri: String! = "test-terms") {
nodeByUri(uri: $uri) {
id
uri
... on NodeWithPostEditorBlocks {
editorBlocks {
__typename
... on CorePostTerms {
prefix
suffix
taxonomy {
__typename
node {
__typename
id
name
}
}
terms {
__typename
nodes {
__typename
id
name
}
}
}
}
}
}
}
```
> feat: Adds terms querying functionality for the CorePostTerms Block.

- .changeset/thirty-knives-know.md
- README.md
- includes/Blocks/Block.php
- tests/unit/BlockTest.php
Related Issue: #222 
This PR introduces _refactoring_ of the `get_attribute_type` method, _new functionality for creating typed attribute objects_ by specifying either in child class or via WP filter.
The previous related PR is [here](https://github.com/wpengine/wp-graphql-content-blocks/pull/336). Comparing with the previous one the current approach is not based on the `block.json` but on the `typed_object_attributes` protected property and WP filter.
---
With this update, you can now query object-type block attributes with each property individually, provided that the **typed structure** is defined in the class `typed_object_attributes` property or through a **WordPress filter**.
The `typed_object_attributes` is a **filterable** array that defines the expected **typed structure** for …
> feat: Adds property typing for an object attribute 

- .changeset/wicked-vans-fly.md
- composer.json
- composer.lock
- wp-graphql-content-blocks.php
Solves #350 and #353 
- Fixes a bug with WPGraphQL Content Blocks causing a fatal error when WPGraphQL is de-activated.  The plugin now requires WPGraphQL
- Added plugin info for WPGraphQL. Tested to 2.0 and requires at least 1.14.5 (same as composer lock file)
Installed WPGraphQL 2.0 on WP 6.7.2 with Local
1. Couldn't enable WPGraphQL Content Blocks until WPGraphQL was enabled
2. WPGraphQL plugin couldn't be disabled when WPGraphQL Content Blocks was activated too
> bug: Fixes WP GraphQL fatal deactivation error

- .changeset/modern-pigs-matter.md
- composer.json
- composer.lock
- patches/blakewilson-wp-enforce-semver/semver-object-key-version.patch
This fixes a fatal error when you go to the Site Health info tab in WordPress. 
Currently used a composer patch as a short term fix.
1. Go to Tools -> Site Health
2. Click on the "info" tab
There shouldn't be a fatal error
1. Check that you cannot enable WPGraphQL Content Blocks without WPGraphQL enabled
2. Check  that you cannot disable WPGraphQL when WPGraphQL Content Blocks is enabled
> bug: Fix semver fatal error

- .changeset/six-boats-exercise.md
- .github/workflows/test-plugin-nightly.yml
- .github/workflows/test-plugin.yml
- readme.txt
Fixes #368 
Tested WPGraphQL Content Blocks on a single and. multisite setup with WordPress 6.8.
> Updated plugin test suite and readme for WordPress 6.8
